# Created by Davi Wall and Felix Pafel for Henkel Adhesives
# Logic: check current kernel version, update the vm, then check the current kernel again and compare to the first version. If different, then restart vm.
---
- hosts: application_servers
  tasks:

    # - name: Start OS updates
    #   apt: name=* state=latest force_apt_get=yes
    #   sudo: true

    - name: Check current installed kernel
      shell: uname -r
      register: current_kernel

    - debug:
        var: current_kernel

    