---
- hosts: application_servers
  tasks:
    - debug:
        msg: ansible_ssh_host

- name: Prepare Host
  import_playbook: bootstrap.yaml

- name: Install Application
  import_playbook: deploy.yaml
