# Created by Davi Wall and Felix Pafel for Henkel Adhesives
# Logic: check current kernel version, update the vm, then check the current kernel again and compare to the first version. If different, then restart vm.
---
- hosts: test_servers
  tasks:

    - name: Start OS updates
      yum: name=* state=latest
      sudo: true

    - name: Check latest installed/available kernel
      shell: "rpm -q kernel --queryformat '%{installtime} %{version}-%{release}.%{arch}\n' | sort -n -k1 | tail -1 | cut -d ' ' -f 2"
      register: new_kernel

    - debug:
        var: new_kernel

    - name: Check current installed kernel
      shell: uname -r
      register: current_kernel

    - debug:
        var: current_kernel

    - name: Stop application
      shell: "{{ stopcommand  }}"
      become: true
      become_user: "{{ appuser }}"
      when: current_kernel.stdout != new_kernel.stdout

    - name: restart server
      shell: sudo shutdown -r
      async: 1
      poll: 0
      when: current_kernel.stdout != new_kernel.stdout

    - name: waiting for server response
      local_action: wait_for host={{ ansible_host }} port=22 state=started delay=100 timeout=300
      sudo: false
      when: current_kernel.stdout != new_kernel.stdout

## This check is currently failing on NON-PROD systems. Gotta check later.
    - name: "Check if AEM is alive"
      uri:
        url: "http://{{ ansible_host }}:4503/etc/healthcheck/50k.html"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
      delegate_to: 127.0.0.1
